import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {TooltipProvider} from "@/components/ui/tooltip";
import React from "react";
import {ThemeProvider} from "@/components/theme-provider";
import ReduxProvider from "@/store";
import AuthProvider from "@/provider/auth_provider";
import {Toaster} from "sonner";
import {AppDataProvider} from "@/provider/dataProvider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Ithute Solutions",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html suppressHydrationWarning
              lang="en"
              className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
        <body className="min-h-full flex flex-col">
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            <ReduxProvider>
                <AuthProvider>
                    <TooltipProvider>
                        <Toaster richColors position="top-right" />
                        <AppDataProvider>
                            {children}
                        </AppDataProvider>
                    </TooltipProvider>
                </AuthProvider>
            </ReduxProvider>
        </ThemeProvider>
        </body>
        </html>
    );
}
