"""add description to fee invoices tooo long_

Revision ID: 33af23ef2f52
Revises: 65130d0f3bb3
Create Date: 2026-05-16 13:35:23.997292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33af23ef2f52'
down_revision: Union[str, Sequence[str], None] = '65130d0f3bb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
