"""add description to fee invoices tooo long

Revision ID: 496b33224685
Revises: a8a3e32072f3
Create Date: 2026-05-18 06:48:54.250255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '496b33224685'
down_revision: Union[str, Sequence[str], None] = 'a8a3e32072f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_employee_payroll_month_year', 'employee_payrolls', ['employee_id', 'payroll_month', 'payroll_year'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_employee_payroll_month_year', 'employee_payrolls', type_='unique')
    # ### end Alembic commands ###
