"""add description to fee invoices tooo long_p

Revision ID: 5ad299184e70
Revises: 33af23ef2f52
Create Date: 2026-05-16 15:38:01.883333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ad299184e70'
down_revision: Union[str, Sequence[str], None] = '33af23ef2f52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fee_invoices', sa.Column('academic_year', sa.String(length=255), nullable=True))
    op.add_column('fee_invoices', sa.Column('penalty_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('fee_invoices', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column('fee_invoices', sa.Column('is_overdue', sa.Boolean(), nullable=True))
    op.add_column('student_credits', sa.Column('academic_year', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_credits', 'academic_year')
    op.drop_column('fee_invoices', 'is_overdue')
    op.drop_column('fee_invoices', 'due_date')
    op.drop_column('fee_invoices', 'penalty_amount')
    op.drop_column('fee_invoices', 'academic_year')
    # ### end Alembic commands ###
