"""add description to fee invoices tooo long

Revision ID: 65130d0f3bb3
Revises: 1df2ac654e29
Create Date: 2026-05-14 21:06:59.247202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65130d0f3bb3'
down_revision: Union[str, Sequence[str], None] = '1df2ac654e29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fee_invoices', sa.Column('school_id', sa.UUID(), nullable=False))
    op.add_column('fee_invoices', sa.Column('description', sa.String(), nullable=True))
    op.add_column('fee_invoices', sa.Column('period_start', sa.Date(), nullable=True))
    op.add_column('fee_invoices', sa.Column('period_end', sa.Date(), nullable=True))
    op.alter_column('fee_invoices', 'student_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('fee_invoices', 'fee_plan_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_foreign_key(None, 'fee_invoices', 'schools', ['school_id'], ['id'])
    op.alter_column('fee_payment_allocations', 'payment_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('fee_payment_allocations', 'invoice_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('fee_payment_allocations', 'amount_allocated',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('fee_payments', 'student_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('fee_payments', 'amount_paid',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fee_payments', 'amount_paid',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('fee_payments', 'student_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('fee_payment_allocations', 'amount_allocated',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('fee_payment_allocations', 'invoice_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('fee_payment_allocations', 'payment_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'fee_invoices', type_='foreignkey')
    op.alter_column('fee_invoices', 'fee_plan_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('fee_invoices', 'student_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('fee_invoices', 'period_end')
    op.drop_column('fee_invoices', 'period_start')
    op.drop_column('fee_invoices', 'description')
    op.drop_column('fee_invoices', 'school_id')
    # ### end Alembic commands ###
