"""add description to fee invoices tooo long

Revision ID: 6db862ffdb9d
Revises: b4c35b5bae84
Create Date: 2026-05-14 16:14:51.550142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6db862ffdb9d'
down_revision: Union[str, Sequence[str], None] = 'b4c35b5bae84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_payment_allocations',
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('amount_allocated', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['fee_invoices.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['fee_payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('fee_invoices', sa.Column('quarter', sa.String(length=255), nullable=True))
    op.alter_column('fee_invoices', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('fee_invoices', 'period_start',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('fee_invoices', 'period_end',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('fee_invoices', 'amount_due',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('fee_payments', 'amount_paid',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.drop_constraint(op.f('fee_payments_invoice_id_fkey'), 'fee_payments', type_='foreignkey')
    op.drop_column('fee_payments', 'invoice_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fee_payments', sa.Column('invoice_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fee_payments_invoice_id_fkey'), 'fee_payments', 'fee_invoices', ['invoice_id'], ['id'])
    op.alter_column('fee_payments', 'amount_paid',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('fee_invoices', 'amount_due',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('fee_invoices', 'period_end',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('fee_invoices', 'period_start',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('fee_invoices', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('fee_invoices', 'quarter')
    op.drop_table('fee_payment_allocations')
    # ### end Alembic commands ###
