"""checking if any error

Revision ID: 7622fe36d7f0
Revises: a4bda8ab35cb
Create Date: 2026-05-05 09:30:36.626591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7622fe36d7f0'
down_revision: Union[str, Sequence[str], None] = 'a4bda8ab35cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent_students',
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('parent_id', 'student_id', 'id'),
    sa.UniqueConstraint('parent_id', 'student_id', name='uix_parent_student')
    )
    op.drop_table('parent_student')
    op.create_unique_constraint(None, 'persons', ['national_id'])
    op.alter_column('students', 'admission_number',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('teachers', 'school_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('teachers', 'employee_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('teachers', 'employee_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('teachers', 'school_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('students', 'admission_number',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'persons', type_='unique')
    op.create_table('parent_student',
    sa.Column('parent_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], name=op.f('parent_student_parent_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('parent_student_student_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('parent_student_pkey'))
    )
    op.drop_table('parent_students')
    # ### end Alembic commands ###
