"""school fee plan

Revision ID: 807ce9b415bd
Revises: b1e383f9a0aa
Create Date: 2026-05-12 08:21:29.845798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '807ce9b415bd'
down_revision: Union[str, Sequence[str], None] = 'b1e383f9a0aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('student_fee_accounts_student_id_fkey'), 'student_fee_accounts', type_='foreignkey')
    op.drop_column('student_fee_accounts', 'fee_structure')
    op.drop_column('student_fee_accounts', 'balance')
    op.drop_column('student_fee_accounts', 'status')
    op.drop_column('student_fee_accounts', 'next_due_date')
    op.drop_column('student_fee_accounts', 'amount_paid')
    op.drop_column('student_fee_accounts', 'student_id')
    op.drop_column('student_fee_accounts', 'total_fee')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_fee_accounts', sa.Column('total_fee', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('student_fee_accounts', sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('student_fee_accounts', sa.Column('amount_paid', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('student_fee_accounts', sa.Column('next_due_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('student_fee_accounts', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('student_fee_accounts', sa.Column('balance', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('student_fee_accounts', sa.Column('fee_structure', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('student_fee_accounts_student_id_fkey'), 'student_fee_accounts', 'students', ['student_id'], ['id'])
    # ### end Alembic commands ###
