"""add notifications

Revision ID: 87b7024dc59e
Revises: 17e18e9ece1e
Create Date: 2026-06-20 15:51:24.283874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87b7024dc59e'
down_revision: Union[str, Sequence[str], None] = '17e18e9ece1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('channel', sa.String(length=255), nullable=True))
    op.drop_constraint(op.f('notifications_user_id_fkey'), 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'user_id')
    op.add_column('users', sa.Column('channel', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'channel')
    op.add_column('notifications', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('notifications_user_id_fkey'), 'notifications', 'users', ['user_id'], ['id'])
    op.drop_column('notifications', 'channel')
    # ### end Alembic commands ###
