"""adding emp number in employee

Revision ID: 8d2ff9daf99d
Revises: a95cc620dc59
Create Date: 2026-05-18 08:57:01.008725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d2ff9daf99d'
down_revision: Union[str, Sequence[str], None] = 'a95cc620dc59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('employee_number', sa.String(length=12), nullable=True))
    op.drop_column('employees', 'emp_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('emp_number', sa.VARCHAR(length=12), autoincrement=False, nullable=True))
    op.drop_column('employees', 'employee_number')
    # ### end Alembic commands ###
