"""add school admin

Revision ID: a4cdc2928dfd
Revises: 29adac6e8d0b
Create Date: 2026-06-06 12:22:06.727443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4cdc2928dfd'
down_revision: Union[str, Sequence[str], None] = '29adac6e8d0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'employee_number',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=30),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'employee_number',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=12),
               existing_nullable=True)
    # ### end Alembic commands ###
