"""create employee management tables

Revision ID: a8a3e32072f3
Revises: 87e989281ef3
Create Date: 2026-05-17 13:28:31.117675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8a3e32072f3'
down_revision: Union[str, Sequence[str], None] = '87e989281ef3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_payments',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('payment_number', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_number')
    )
    op.create_table('employee_payrolls',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('payroll_month', sa.String(), nullable=False),
    sa.Column('payroll_year', sa.Integer(), nullable=False),
    sa.Column('basic_salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('allowances', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('deductions', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('gross_salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('net_salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_salary_structures',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('basic_salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('housing_allowance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('transport_allowance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('medical_allowance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('overtime_allowance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('other_allowance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tax_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pension_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_credits',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('source_payment_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['source_payment_id'], ['employee_payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_payment_allocations',
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('payroll_id', sa.UUID(), nullable=False),
    sa.Column('amount_allocated', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['employee_payments.id'], ),
    sa.ForeignKeyConstraint(['payroll_id'], ['employee_payrolls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_payment_allocations')
    op.drop_table('employee_credits')
    op.drop_table('employee_salary_structures')
    op.drop_table('employee_payrolls')
    op.drop_table('employee_payments')
    # ### end Alembic commands ###
