"""adding emp number in employee

Revision ID: a95cc620dc59
Revises: 496b33224685
Create Date: 2026-05-18 08:49:49.937104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a95cc620dc59'
down_revision: Union[str, Sequence[str], None] = '496b33224685'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('emp_number', sa.String(length=12), nullable=True))
    op.add_column('teachers', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'teachers', ['user_id'])
    op.create_foreign_key(None, 'teachers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teachers', type_='foreignkey')
    op.drop_constraint(None, 'teachers', type_='unique')
    op.drop_column('teachers', 'user_id')
    op.drop_column('employees', 'emp_number')
    # ### end Alembic commands ###
