"""school school = r ) invoice_number

Revision ID: acca80567397
Revises: c8aec2598f8e
Create Date: 2026-05-14 03:57:39.552432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acca80567397'
down_revision: Union[str, Sequence[str], None] = 'c8aec2598f8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fee_invoices', sa.Column('invoice_number', sa.String(length=12), nullable=False))
    op.alter_column('fee_invoices', 'amount_due',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('fee_invoices', 'amount_paid',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('fee_invoices', 'balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.create_unique_constraint(None, 'fee_invoices', ['invoice_number'])
    op.add_column('fee_payments', sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=True))
    op.drop_column('fee_payments', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fee_payments', sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('fee_payments', 'amount_paid')
    op.drop_constraint(None, 'fee_invoices', type_='unique')
    op.alter_column('fee_invoices', 'balance',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('fee_invoices', 'amount_paid',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('fee_invoices', 'amount_due',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('fee_invoices', 'invoice_number')
    # ### end Alembic commands ###
