"""school fee plan

Revision ID: b1e383f9a0aa
Revises: 53eb504d05b9
Create Date: 2026-05-11 20:28:46.199225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1e383f9a0aa'
down_revision: Union[str, Sequence[str], None] = '53eb504d05b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fee_payments', 'paid_at')
    op.add_column('fee_plans', sa.Column('first_quarter', sa.Float(), nullable=False))
    op.add_column('fee_plans', sa.Column('second_quarter', sa.Float(), nullable=False))
    op.add_column('fee_plans', sa.Column('third_quarter', sa.Float(), nullable=False))
    op.add_column('fee_plans', sa.Column('fourth_quarter', sa.Float(), nullable=False))
    op.drop_column('fee_plans', 'total_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fee_plans', sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('fee_plans', 'fourth_quarter')
    op.drop_column('fee_plans', 'third_quarter')
    op.drop_column('fee_plans', 'second_quarter')
    op.drop_column('fee_plans', 'first_quarter')
    op.add_column('fee_payments', sa.Column('paid_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
