"""school db modified

Revision ID: b79b46dc6b15
Revises: 2c402d4e29a0
Create Date: 2026-04-29 08:17:28.876332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b79b46dc6b15'
down_revision: Union[str, Sequence[str], None] = '2c402d4e29a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('schools_email_key'), 'schools', type_='unique')
    op.drop_constraint(op.f('schools_phone_key'), 'schools', type_='unique')
    op.drop_column('schools', 'title_deed_number')
    op.drop_column('schools', 'website')
    op.drop_column('schools', 'lease_agreement_reference')
    op.drop_column('schools', 'land_ownership_type')
    op.drop_column('schools', 'city')
    op.drop_column('schools', 'financial_notes')
    op.drop_column('schools', 'email')
    op.drop_column('schools', 'country')
    op.drop_column('schools', 'phone')
    op.drop_column('schools', 'district')
    op.drop_column('schools', 'bank_name')
    op.drop_column('schools', 'address')
    op.drop_column('schools', 'account_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('account_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('schools', sa.Column('address', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('schools', sa.Column('bank_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('schools', sa.Column('district', sa.VARCHAR(length=255), server_default=sa.text("'Maseru'::character varying"), autoincrement=False, nullable=False))
    op.add_column('schools', sa.Column('phone', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('schools', sa.Column('country', sa.VARCHAR(length=100), server_default=sa.text("'Lesotho'::character varying"), autoincrement=False, nullable=True))
    op.add_column('schools', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('schools', sa.Column('financial_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('schools', sa.Column('city', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('schools', sa.Column('land_ownership_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('schools', sa.Column('lease_agreement_reference', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('schools', sa.Column('website', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('schools', sa.Column('title_deed_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('schools_phone_key'), 'schools', ['phone'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('schools_email_key'), 'schools', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
