"""add description to fee invoices koop

Revision ID: c3bcad73a91d
Revises: 76e54396c31e
Create Date: 2026-05-14 14:20:34.282855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3bcad73a91d'
down_revision: Union[str, Sequence[str], None] = '76e54396c31e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fee_invoices', 'invoice_number',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=16),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fee_invoices', 'invoice_number',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)
    # ### end Alembic commands ###
