"""school school = r)

Revision ID: c8aec2598f8e
Revises: ee089c3b277b
Create Date: 2026-05-13 08:30:40.790861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8aec2598f8e'
down_revision: Union[str, Sequence[str], None] = 'ee089c3b277b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fee_plans_school_id_fkey'), 'fee_plans', type_='foreignkey')
    op.drop_column('fee_plans', 'school_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fee_plans', sa.Column('school_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fee_plans_school_id_fkey'), 'fee_plans', 'schools', ['school_id'], ['id'])
    # ### end Alembic commands ###
