"""student and teacher

Revision ID: e317ab37aa1a
Revises: d18d8cc8289f
Create Date: 2026-05-05 09:01:21.868124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e317ab37aa1a'
down_revision: Union[str, Sequence[str], None] = 'd18d8cc8289f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('parents_user_id_fkey'), 'parents', type_='foreignkey')
    op.create_foreign_key(None, 'parents', 'users', ['id'], ['id'])
    op.drop_column('parents', 'user_id')
    op.drop_constraint(op.f('teachers_user_id_fkey'), 'teachers', type_='foreignkey')
    op.create_foreign_key(None, 'teachers', 'users', ['id'], ['id'])
    op.drop_column('teachers', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'teachers', type_='foreignkey')
    op.create_foreign_key(op.f('teachers_user_id_fkey'), 'teachers', 'users', ['user_id'], ['id'])
    op.add_column('parents', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'parents', type_='foreignkey')
    op.create_foreign_key(op.f('parents_user_id_fkey'), 'parents', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
