"""grade, class and school table has been modified

Revision ID: e4cc5d67c6c9
Revises: 57b15f2778a2
Create Date: 2026-05-04 10:47:08.810251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4cc5d67c6c9'
down_revision: Union[str, Sequence[str], None] = '57b15f2778a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('grade_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('classes_school_id_fkey'), 'classes', type_='foreignkey')
    op.create_foreign_key(None, 'classes', 'grades', ['grade_id'], ['id'])
    op.drop_column('classes', 'grade_level')
    op.drop_column('classes', 'school_id')
    op.drop_constraint(op.f('grades_school_id_fkey'), 'grades', type_='foreignkey')
    op.drop_column('grades', 'school_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('school_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('grades_school_id_fkey'), 'grades', 'schools', ['school_id'], ['id'])
    op.add_column('classes', sa.Column('school_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('classes', sa.Column('grade_level', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'classes', type_='foreignkey')
    op.create_foreign_key(op.f('classes_school_id_fkey'), 'classes', 'schools', ['school_id'], ['id'])
    op.drop_column('classes', 'grade_id')
    # ### end Alembic commands ###
