"""add notifications

Revision ID: ea117412fa48
Revises: 47fa1140f063
Create Date: 2026-06-20 15:55:26.453410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea117412fa48'
down_revision: Union[str, Sequence[str], None] = '47fa1140f063'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('channel', sa.String(length=255), nullable=True))
    op.drop_column('notifications', 'channels')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('channels', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('notifications', 'channel')
    # ### end Alembic commands ###
