"""school school = relationship(
        School,
        back_populates=fee_configuration
    )

Revision ID: ee089c3b277b
Revises: 172916a0ed2a
Create Date: 2026-05-13 07:22:02.188022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee089c3b277b'
down_revision: Union[str, Sequence[str], None] = '172916a0ed2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fee_plans', sa.Column('feeConfig_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'fee_plans', 'school_fee_configuration', ['feeConfig_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fee_plans', type_='foreignkey')
    op.drop_column('fee_plans', 'feeConfig_id')
    # ### end Alembic commands ###
