"""add description to fee invoices tooo long_p_

Revision ID: f37b95f70306
Revises: 5ad299184e70
Create Date: 2026-05-16 16:43:38.481323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f37b95f70306'
down_revision: Union[str, Sequence[str], None] = '5ad299184e70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fee_payments', sa.Column('payment_number', sa.String(length=16), nullable=False))
    op.create_unique_constraint(None, 'fee_payments', ['payment_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fee_payments', type_='unique')
    op.drop_column('fee_payments', 'payment_number')
    # ### end Alembic commands ###
