"""school fee configuration

Revision ID: f4ce7ba18dcd
Revises: 688417c77c3d
Create Date: 2026-05-11 13:50:41.978941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4ce7ba18dcd'
down_revision: Union[str, Sequence[str], None] = '688417c77c3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_fee_configuration',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('year_start', sa.Date(), nullable=False),
    sa.Column('year_end', sa.Date(), nullable=False),
    sa.Column('fee_structure', sa.Enum('QUARTERLY', 'MONTHLY', 'ANNUAL', name='feestructuretype'), nullable=False),
    sa.Column('allow_partial_payments', sa.Boolean(), nullable=True),
    sa.Column('allow_late_payments', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('school_fee_configuration')
    # ### end Alembic commands ###
