from io import BytesIO

from fastapi import APIRouter, Depends
from fastapi.responses import Response
from openpyxl import Workbook
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from sqlalchemy.orm import Session

from database.multi_tenant_school_management.models import School
from database.session import get_db
from routes.reports import REPORT_ROLES, school_management_overview
from utils.school_context import SchoolContext, require_school_roles

router = APIRouter(prefix="/reports/export", tags=["School Report Exports"])


def _overview(db: Session, context: SchoolContext):
    return school_management_overview(db=db, context=context)


def _school_name(db: Session, context: SchoolContext) -> str:
    school = db.get(School, context.school_id)
    return school.name if school else "!thute Tutor School"


def _rows(report: dict):
    return [
        ("Generated on", report["generated_on"]),
        ("Active learners", report["people"]["active_students"]),
        ("Teachers", report["people"]["teachers"]),
        ("Employees", report["people"]["employees"]),
        ("Current academic year", report["academics"]["current_year"] or "Not set"),
        ("Current term", report["academics"]["current_term"] or "Not set"),
        ("Assessments", report["academics"]["assessments"]),
        ("Published assessments", report["academics"]["published_assessments"]),
        ("Average published score %", report["academics"]["average_published_score_percent"]),
        ("Attendance records", report["attendance"]["records"]),
        ("Attendance rate %", report["attendance"]["attendance_rate_percent"]),
        ("Amount invoiced", report["finance"]["amount_invoiced"]),
        ("Cash received", report["finance"]["cash_received"]),
        ("Outstanding fees", report["finance"]["outstanding_balance"]),
        ("Overdue invoices", report["finance"]["overdue_invoices"]),
        ("Net payroll", report["payroll"]["net_payroll"]),
        ("Payroll paid", report["payroll"]["amount_paid"]),
        ("Payroll outstanding", report["payroll"]["outstanding_balance"]),
    ]


@router.get("/management.xlsx")
def export_management_xlsx(
    db: Session = Depends(get_db),
    context: SchoolContext = Depends(require_school_roles(*REPORT_ROLES)),
):
    report = _overview(db, context)
    school_name = _school_name(db, context)
    workbook = Workbook()
    sheet = workbook.active
    sheet.title = "Management Overview"
    sheet.append([school_name])
    sheet.append(["!thute Tutor Management Report"])
    sheet.append([])
    sheet.append(["Metric", "Value"])
    for label, value in _rows(report):
        sheet.append([label, value])
    sheet.column_dimensions["A"].width = 32
    sheet.column_dimensions["B"].width = 24
    stream = BytesIO()
    workbook.save(stream)
    return Response(
        content=stream.getvalue(),
        media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        headers={"Content-Disposition": 'attachment; filename="ithute-tutor-management-report.xlsx"'},
    )


@router.get("/management.pdf")
def export_management_pdf(
    db: Session = Depends(get_db),
    context: SchoolContext = Depends(require_school_roles(*REPORT_ROLES)),
):
    report = _overview(db, context)
    school_name = _school_name(db, context)
    stream = BytesIO()
    pdf = canvas.Canvas(stream, pagesize=A4)
    width, height = A4
    y = height - 55
    pdf.setTitle(f"{school_name} - !thute Tutor Management Report")
    pdf.setFont("Helvetica-Bold", 16)
    pdf.drawString(45, y, school_name[:70])
    y -= 24
    pdf.setFont("Helvetica", 10)
    pdf.drawString(45, y, f"!thute Tutor Management Report · {report['generated_on']}")
    y -= 28
    for label, value in _rows(report):
        if y < 60:
            pdf.showPage()
            y = height - 55
        pdf.setFont("Helvetica-Bold", 9)
        pdf.drawString(45, y, str(label)[:42])
        pdf.setFont("Helvetica", 9)
        pdf.drawString(260, y, "—" if value is None else str(value)[:52])
        y -= 18
    pdf.setFont("Helvetica", 8)
    pdf.drawRightString(width - 45, 35, "Generated by !thute Tutor")
    pdf.save()
    return Response(
        content=stream.getvalue(),
        media_type="application/pdf",
        headers={"Content-Disposition": 'attachment; filename="ithute-tutor-management-report.pdf"'},
    )
